services:
  forum:
    build: ./
    ports:
      - 8000:8000
    networks:
      - forum
    depends_on:
      db:
        condition: service_healthy
    env_file: ".env"

  db:
    image: postgres:latest
    restart: on-failure
    volumes:
      - forum:/var/lib/postgresql/data
    env_file: ".env"
    ports:
      - 5432:5432
    networks:
      - forum
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  forum:

volumes:
  forum:
